const REACTION_CATALOG = [
  { emoji: "👍", label: "Strong Yes", category: "Approval", linkedInType: "like", keywords: ["approve", "yes", "agree"] },
  { emoji: "✅", label: "Checked", category: "Approval", linkedInType: "like", keywords: ["done", "verified", "clear"] },
  { emoji: "💯", label: "100 Percent", category: "Approval", linkedInType: "like", keywords: ["perfect", "agree", "strong"] },
  { emoji: "👏", label: "Great Work", category: "Celebrate", linkedInType: "celebrate", keywords: ["applause", "great", "win"] },
  { emoji: "🏆", label: "Big Win", category: "Celebrate", linkedInType: "celebrate", keywords: ["achievement", "award", "success"] },
  { emoji: "🎉", label: "Milestone", category: "Celebrate", linkedInType: "celebrate", keywords: ["milestone", "launch", "party"] },
  { emoji: "🚀", label: "Launch", category: "Celebrate", linkedInType: "celebrate", keywords: ["ship", "go", "growth"] },
  { emoji: "🤝", label: "We Got You", category: "Support", linkedInType: "support", keywords: ["help", "support", "together"] },
  { emoji: "🫶", label: "Much Support", category: "Support", linkedInType: "support", keywords: ["care", "solidarity", "community"] },
  { emoji: "💙", label: "Team Support", category: "Support", linkedInType: "support", keywords: ["team", "support", "care"] },
  { emoji: "🙏", label: "Respect", category: "Support", linkedInType: "support", keywords: ["respect", "thanks", "gratitude"] },
  { emoji: "❤️", label: "Love This", category: "Love", linkedInType: "love", keywords: ["love", "amazing", "favorite"] },
  { emoji: "😍", label: "Obsessed", category: "Love", linkedInType: "love", keywords: ["wow", "love", "excellent"] },
  { emoji: "🔥", label: "On Fire", category: "Love", linkedInType: "love", keywords: ["hot", "strong", "awesome"] },
  { emoji: "🌟", label: "Star Move", category: "Love", linkedInType: "love", keywords: ["star", "elite", "quality"] },
  { emoji: "💡", label: "Sharp Insight", category: "Insight", linkedInType: "insightful", keywords: ["idea", "insight", "smart"] },
  { emoji: "🧠", label: "Deep Thinking", category: "Insight", linkedInType: "insightful", keywords: ["thinking", "strategy", "mind"] },
  { emoji: "📈", label: "Strong Signal", category: "Insight", linkedInType: "insightful", keywords: ["trend", "data", "growth"] },
  { emoji: "📊", label: "Great Data", category: "Insight", linkedInType: "insightful", keywords: ["metrics", "analysis", "numbers"] },
  { emoji: "🧩", label: "Good Framing", category: "Insight", linkedInType: "insightful", keywords: ["framework", "systems", "clarity"] },
  { emoji: "😂", label: "Actually Funny", category: "Funny", linkedInType: "funny", keywords: ["lol", "funny", "laugh"] },
  { emoji: "😄", label: "Love This Joke", category: "Funny", linkedInType: "funny", keywords: ["joke", "laugh", "smile"] },
  { emoji: "😎", label: "Cool Move", category: "Funny", linkedInType: "funny", keywords: ["cool", "slick", "vibe"] },
  { emoji: "🤖", label: "Automation Win", category: "Tech", linkedInType: "insightful", keywords: ["ai", "automation", "tech"] },
  { emoji: "🛠️", label: "Built Well", category: "Tech", linkedInType: "like", keywords: ["engineering", "build", "craft"] },
  { emoji: "⚙️", label: "Solid Process", category: "Tech", linkedInType: "insightful", keywords: ["operations", "process", "system"] },
  { emoji: "🔍", label: "Great Breakdown", category: "Insight", linkedInType: "insightful", keywords: ["analysis", "detail", "research"] },
  { emoji: "🧭", label: "Great Direction", category: "Leadership", linkedInType: "insightful", keywords: ["direction", "strategy", "lead"] },
  { emoji: "🧱", label: "Strong Foundation", category: "Leadership", linkedInType: "like", keywords: ["foundation", "principles", "discipline"] },
  { emoji: "🫡", label: "Respect This", category: "Leadership", linkedInType: "support", keywords: ["respect", "honor", "leadership"] },
  { emoji: "📣", label: "Well Said", category: "Communication", linkedInType: "insightful", keywords: ["communication", "clear", "message"] },
  { emoji: "✍️", label: "Great Writing", category: "Communication", linkedInType: "insightful", keywords: ["writing", "post", "narrative"] },
  { emoji: "🔗", label: "Strong Connection", category: "Networking", linkedInType: "support", keywords: ["network", "connection", "community"] },
  { emoji: "🌍", label: "Global Impact", category: "Impact", linkedInType: "celebrate", keywords: ["impact", "global", "change"] },
  { emoji: "♻️", label: "Sustainable", category: "Impact", linkedInType: "support", keywords: ["sustainability", "planet", "responsible"] },
  { emoji: "📚", label: "Learned A Lot", category: "Learning", linkedInType: "insightful", keywords: ["learning", "knowledge", "educational"] },
  { emoji: "🧑‍🏫", label: "Excellent Teaching", category: "Learning", linkedInType: "insightful", keywords: ["mentor", "coach", "teaching"] },
  { emoji: "🎯", label: "Nailed It", category: "Execution", linkedInType: "like", keywords: ["execution", "focus", "target"] },
  { emoji: "🧪", label: "Great Experiment", category: "Execution", linkedInType: "insightful", keywords: ["test", "experiment", "learn"] },
  { emoji: "⚡", label: "Fast Execution", category: "Execution", linkedInType: "celebrate", keywords: ["speed", "fast", "ship"] }
];

const REACTION_CATALOG_CATEGORIES = [
  "All",
  ...Array.from(new Set(REACTION_CATALOG.map((item) => item.category))).sort()
];
